---
title: "Text_Ex"
author: "Yao"
date: "2018年7月17日"
output: html_document
---
# 文字雲製作
## 導入老師寫的函式與其他資源
```{r}
source("pttTestFunction.R")
library(NLP)
library(tm)
library(jiebaRD)
library(jiebaR)
library(RColorBrewer)
library(knitr)
library(wordcloud)
library(jiebaR)
library(wordcloud2)
```

## 進行資料蒐集，並存成文字檔
```{r}
id = c(6443:6453)
name_post <- "MobileComm" # 目標是手機版
URL = paste0("https://www.ptt.cc/bbs/",name_post,"/index", id, ".html")
filename = paste0(id, ".txt")
Open_Star <- c(FALSE) # 這是開關
if(Open_Star == TRUE){
pttTestFunction(URL[1], filename[1])
mapply(pttTestFunction,
URL = URL, filename = filename)}
```

## 進行文字清洗
```{r setup, include=FALSE}
## 2
rm(list=ls(all.names = TRUE))
filenames <- list.files(getwd(), pattern="*.txt")
files <- lapply(filenames, readLines)
docs <- Corpus(VectorSource(files))
#移除可能有問題的符號
toSpace <- content_transformer(function(x, pattern) {
  return (gsub(pattern, " ", x))
}
)
ignore_text <- c(
"※","◆","‧","推","噓","的","我","是","了","有",
"用","在","沒","還","看","要","啦","多","上","說",
"真",
"也","就","都","不","被","到","好","會","但","你",
"跟","能","嗎","更","只","出","阿","是","吧","是",
"這","為","啊","喔","又","和","很","過","再","因",
"和","標題","網址","什麼","看板","作者","可以",
"發信站","批踢踢實業坊","[a-zA-Z]")
for(ignore in ignore_text){
docs<- tm_map(docs, toSpace, ignore)
}
#移除標點符號 (punctuation)
#移除數字 (digits)、空白 (white space)
docs <- tm_map(docs, removePunctuation)
docs <- tm_map(docs, removeNumbers)
docs <- tm_map(docs, stripWhitespace)
docs
#
```
## 詞頻矩陣
```{r}
#
mixseg = worker()
jieba_tokenizer=function(d){
  unlist(segment(d[[1]],mixseg))
}
seg = lapply(docs, jieba_tokenizer)
freqFrame = as.data.frame(table(unlist(seg)))
freqFrame = freqFrame[order(freqFrame$Freq,decreasing=TRUE), ]
kable(head(freqFrame), format = "markdown")
```
## 建立文字雲
```{r}
wordcloud(freqFrame$Var1,freqFrame$Freq,
          scale=c(6,0.5),min.freq=10,max.words=100,
          random.order=FALSE, random.color=TRUE, 
          rot.per=0, colors=brewer.pal(8, "Dark2"),
          ordered.colors=FALSE,use.r.layout=FALSE,
          fixed.asp=FALSE)
```

* 手機版想必手機這個字最多呢！

## 其他的文字雲

```{r}
wordcloud2(freqFrame[1:300,], size = 0.5,shape = 'pentagon')
```

